apiVersion: v1
kind: Namespace
metadata:
  name: first-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: first-namespace
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
