apiVersion: v1
kind: Namespace
metadata:
  name: second-namespace

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: second-namespace
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
